CREATE SEQUENCE pilot_ids INCREMENT BY 1 MINVALUE 1 MAXVALUE 9223372036854775807 START 1000001 NO CYCLE;;
CREATE TABLE Pilots(PilotID INTEGER DEFAULT(nextval('pilot_ids')) PRIMARY KEY, UpdateTime TIMESTAMP, Status ENUM('Running', 'Waiting', 'Done', 'Failed'));;
CREATE TABLE PilotAttributes(PilotID INTEGER PRIMARY KEY, Cores USMALLINT, MemoryMB UINTEGER, FOREIGN KEY (PilotID) REFERENCES Pilots(PilotID));;

